name: Deploy Static Webpage

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/deployment.yml'
  workflow_dispatch:

jobs:
  deploy-site:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Sync S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          SOURCE_DIR: './src'
          AWS_REGION: 'us-west-1'
          AWS_S3_BUCKET: 'lobo-and-zorra-static-website-bucket'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}