name: Infrastructure Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/infra-deployment.yml'
  workflow_dispatch:

env:
  TF_LOG: INFO
  TF_VERSION: 1.2.7
  environment: dev
  TF_WORKING_DIR: "./terraform"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  security-check:
    name: Security Check
    uses: ./.github/workflows/tfsec.yml

  deploy-infrastructure:
    needs: [security-check]
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=${{ env.environment }}-${{ github.sha }}.tfplan -var-file=terraform.tfvars

      - name: Terraform Apply
        run: terraform apply "${{ env.environment }}-${{ github.sha }}.tfplan"